apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-extension
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: extension
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
spec:
  template:
    spec:
      containers:
        - name: webhooks-extension
          env:
          - name: WEBHOOK_CALLBACK_URL
            value: http://listener.IPADDRESS.nip.io
