kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-minimal
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
rules:
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  - taskruns
  verbs:
  - get
- apiGroups:
  - triggers.tekton.dev
  resources:
  - triggerbindings
  - triggertemplates
  - eventlisteners
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  - taskruns
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
  - watch