apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-webhooks-extension
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
