apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-webhooks-extension-eventlistener-minimal
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-minimal
subjects:
- kind: ServiceAccount
  name: tekton-webhooks-extension-eventlistener
  namespace: tekton-pipelines