apiVersion: v1
kind: Service
metadata:
  name: tekton-webhooks-extension-validator
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: validator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: validator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080