apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-webhooks-extension-validator
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: validator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: validator
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-webhooks-extension
  template:
    metadata:
      labels:
        app.kubernetes.io/component: validator
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-webhooks-extension
    spec:
      containers:
        - name: validate
          image: interceptorImage
          env:
            - name: INSTALLED_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: tekton-webhooks-extension