apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-extension
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: extension
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
spec:
  template:
    spec:
      containers:
        - name: webhooks-extension
          env:
          # If this endpoint's protocol is https, tls will be enabled on the github webhook
          # openshift_master_default_subdomain usually of the format 'apps.host.company.com'
          - name: WEBHOOK_CALLBACK_URL
            value: https://el-tekton-webhooks-eventlistener-tekton-pipelines.{openshift_master_default_subdomain}
          # If the WEBHOOK_CALLBACK_URL's protocol is https, should tls verification be enabled/disabled?
          # See https://github.com/tektoncd/experimental/issues/399
          - name: PLATFORM
            value: openshift
